name: First Workflow
on: workflow_dispatch # manually trigger this workflow
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!" # define a command to execute
      - name: Print goodbye
        run: echo "Done - bye!"
